### ISSUE TITLE
Generalize stemmers

### ISSUE THREAD

**Issue by roedoejet** [MotherTongues/mothertongues#15]
Instead of just supporting English, we should support the intersection of supported languages in https://www.npmjs.com/package/snowball-stemmers and https://www.nltk.org/api/nltk.stem.snowball.html

**Comment by dhdaines** [comment]
Good idea!  Should not be too hard to implement... I will take a look

**Comment by roedoejet** [comment]
Yea, it didn't look too hard, you just pass a language name in to the NPM package factory. NLTK looks like it has all of the languages separated into different classes, but we could write our own factory function too.

**Comment by roedoejet** [comment]
I'm going to [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) this for now unless somebody would like to work on it. If you see this issue and are trying to get stemmers to work for a language other than English, please post here and I will re-open the issue.
