### ISSUE TITLE
JSON parser enhancements

### ISSUE THREAD

**Issue by dhdaines** [MotherTongues/mothertongues#16]
The JSON parser doesn't quite handle the Turtle Mountain Michif dictionary (which is why I ended up with the long exceptions for "empty" dictionaries).  I'm putting an issue here as a placeholder until I know what the actual problem is at which point I'll submit a PR as well!

**Comment by roedoejet** [comment]
Hm, dang! OK - yes, please keep me posted, or post a minimal example here I can debug from. Thanks @dhdaines !
