### ISSUE TITLE
Model Validator on WeightedLevensteinConfig has inaccurate messaging/validation

### ISSUE THREAD

**Issue by pandersity** [MotherTongues/mothertongues#23]
The message as part of `convert_sub_costs()` states that  `For each entry you must have two characters and a number between 0.0 and 1.0.`

However, I can put in numbers greater than 1.0, and this message never gets hit.

Either need to change message or add explicit validation on the number.

(I prefer adding validation, but wasn't sure if this is the right place to do it, since `convert_sub_costs()` only triggers when reading weights from a file...)

Thoughts?

![image](https://github.com/MotherTongues/mothertongues/assets/8306507/61da98e4-b45d-4760-af4b-02bbfdb218dd)

**Comment by pandersity** [comment]
@roedoejet , if you'd like to see what I'm talking about in action, pull down https://github.com/MotherTongues/mothertongues/tree/dev.unittests/config-data-tests

and run unit tests. Commit 1744a9674272dccc65f21664fa3eaac2a7727d70 fails unit tests because code behave differently than expected based on error message.

**Comment by roedoejet** [comment]
Ah, good catch @pandersity ! I added a PR here that catches it in pydantic: https://github.com/MotherTongues/mothertongues/pull/24
