### ISSUE TITLE
Formatting of lists appears to be broken in the docs

### ISSUE THREAD

**Issue by roedoejet** [MotherTongues/mothertongues#28]
I'm just seeing that the hyphens used to indicate list elements don't appear to be rendering properly:

![image](https://github.com/MotherTongues/mothertongues/assets/14815080/067759cb-9e8f-40be-aa39-1534de81f082)

Were they rendering for you locally @pandersity or is there a different syntax we should be using?

**Comment by pandersity** [comment]
@roedoejet - I missed a few new lines for correct formatting. sorry about that. Should be fixed now in PR #29
